feat(core): QnA CRUD 기능 개발
sickgyun/sickgyun-server pull request #18
Opened 2023-12-29 02:25 UTC by Woongbin06

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #15 

<br>

## 📄 개요
[//]: # (작업 내용을 간단히 요약해서 적습니다.)
[//]: # (예시: 유저 회원가입 기능을 만들었습니다.)

> QnA CRUD 기능을 만들었습니다.

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- QnA 생성 API를 만들었습니다.
- QnA 조회 API를 만들었습니다.
- QnA 삭제 API를 만들었습니다.
- QnA 수정 API를 만들었습니다.
- QnA 조회 시 카테고리별 필터링 기능을 만들었습니다.

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [x] 테스트를 완료했나요?
- [ ] API 문서를 작성했나요?
- [ ] 코드 컨벤션을 준수했나요?
- [x] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-01-01 14:02 UTC, jacobhboy commented
수고하셨습니다!! 코드 컨벤션 처음으로 맞춘다고 정말 고생 많으셨어요! 리뷰 시작하기 전에 결국 해낸 웅빈님을 칭찬합니다 ㅋㅋㅋㅋ

2024-01-01 14:35 UTC, jacobhboy requested changes
개발하시느라 수고하셨습니다..! 조금만 더 고민해줘요 ㅎ

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/CommandQnAService.java
> +	public void updateQnA(Long qnAId, CreateQnARequest request) {
저는 DTO는 presentation 레이어에서 사용하는 객체로 외부와 소통은 언제나 변할 수 있기 때문에 사용하는 객체라고 생각해요. 그래서 저는 DTO가 비즈니스 레이어에는 내려가면 안된다고 생각해요. 비즈니스 레이어에서는 도메인 객체를 사용하는 것이 맞다고 생각하는데 웅빈님의 생각은 어떠하신가요?
[비즈니스 레이어와 DTO](https://www.youtube.com/watch?v=Zs4VYXudYIQ&t=440s)

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +			.toList();
여기도 ResponseDto를 참조하고 있네요. 그리고 같은 그리고 stream과 map이 여기 있으니 비즈니스의 흐름을 알기가 어려운 것 같아요. 비즈니스의 흐름이 잘 보이게 생각하고 개선한다면 Controller에서 List<도메인 클래스> 받은 것을 QnAResponse.of()로 변환하는 것이 좋을 것 같아요.

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +		return QnAResponse.from(qna);
함수명 from 보다 of가 더 적합하다고 생각해요.

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/implementation/QnACreator.java
> +		qnARepository.save(qnA);
클래스 이름에 creator니 save 대신 create이 함수 명으로 더 적합해보여요!

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/presentation/qna/QnAController.java
> +	@ResponseStatus(HttpStatus.NO_CONTENT)
깔끔하고 좋습니다~!

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/presentation/qna/QnAController.java
> +		return queryQnAService.findAllByCategory(category);
이 부분에서 저는 카테고리 판단하는 것도 엄연한 비즈니스 흐름으로 생각하는데, Presentation 레이어에서 처리 되서 비즈니스 레이어에서는 흐름을 볼 수 없다는게 아쉽게 느껴져요. 웅빈님은 어떻게 생각하세요?

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/qna/QnA.java
> +		this.createTime = LocalDateTime.now();
@CreatedDate라는 어노테이션도 있어요!

2024-01-01 14:35 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/presentation/qna/QnAController.java
> +	@DeleteMapping("/{qna-id}")
이부분도 http 통신이라서 케밥 케이스를 사용하셨군요! 나중에 spring docs쓰거나 swagger 쓸 때 더 표준에 적합하게 보여서 좋을 것 같습니다~

2024-01-01 15:13 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +		return QnAResponse.from(qna);
매개 변수가 한 개일 때는 of보다는 from을 주로 사용하는 걸로 알고 있어요.
[정적 팩토리 메서드](https://sun-22.tistory.com/84)

2024-01-01 15:22 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/core/service/qna/CommandQnAService.java
> +	public void updateQnA(Long qnAId, CreateQnARequest request) {
저는 DTO가 비지니스 레이어에 내려가는 것 보다 도메인을 프레젠테이션 레이어에 노출시키지 않는 것이 더 안정적이라 생각해 외부와 소통만 하는 DTO를 비지니스 레이어에 사용하고 presentation 영역에서는 도메인 객체를 호출하지 않도록 하는 게 좋은 것 같아서 저렇게 코드를 작성했어요.

2024-01-01 15:35 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +		return QnAResponse.from(qna);
매개 변수가 한 개일 때는 of보다는 from을 주로 사용하는 걸로 알고 있어요. 하지만 확장성을 고려해 of를 사용하는 것도 좋을 것 같아요 ~
[정적 팩토리 메서드](https://sun-22.tistory.com/84)

2024-01-01 15:38 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/core/presentation/qna/QnAController.java
> +		return queryQnAService.findAllByCategory(category);
전 하나의 비지니스 로직에서 한 종류의 쿼리만 실행되는 것이 책임 분할이 잘 된다고 생각했는데 창보님 말대로 비지니스 레이어에서 흐름을 볼 수 없다는 점이 있는 것 같네요!

2024-01-01 23:00 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/CommandQnAService.java
> +	public void updateQnA(Long qnAId, CreateQnARequest request) {
dto.toEntity()이렇게 작성하면 노출하지 않고, 비즈니스 레이어에도 내려가지 않게 할 수 있습니다!

2024-01-01 23:02 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +		return QnAResponse.from(qna);
명명규칙에 대해서 자세히 몰랐는데 from이 더 적합한 것 같네요!

2024-01-02 01:42 UTC, jacobhboy approved these changes
수고하셨슴니당~ 개발일지 작성할 타이밍인 것 같네요~

2024-01-02 01:42 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/CommandQnAService.java
> +		qnAUpdater.update(updatableQnA, qnA);
굳굳 👍

2024-01-02 01:42 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/core/service/qna/QueryQnAService.java
> +		return qnAReader.readAllByCategory(category);
🙂 최고네요

2024-01-02 01:43 UTC, merged