feat(commnet) : 댓글 기능 구현
sickgyun/sickgyun-server pull request #33
Opened 2024-01-03 01:16 UTC by Woongbin06

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #29 

<br>

## 📄 개요
[//]: # (작업 내용을 간단히 요약해서 적습니다.)
[//]: # (예시: 유저 회원가입 기능을 만들었습니다.)

> 댓글 기능을 만들었습니다.

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- 댓글 생성 기능
- 댓글 수정 기능
- 댓글 삭제 기능
- QnA에 있는 댓글 조회 기능

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [x] 테스트를 완료했나요?
- [x] API 문서를 작성했나요?
- [x] 코드 컨벤션을 준수했나요?
- [x] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-01-03 06:59 UTC, jacobhboy requested changes
수고하셨습니다~~~~ 빠르게 MVP 개발 끝내봅시다

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	private QnA qnA;
QnA가 삭제됐을 때 Comment도 제거되야하니 orphanremoval을 설정해주는게 좋을 것 같아요!

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	}
검증로직은 implement에서 validator 생성 후 구현하는게 우리 팀 코드 규칙이라서 준수 부탁드립니다!

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	}
validator에서 호출하는 것이군요..! 그런데 writer에서 equals에 대한 구현없이 사용하면 동일성 비교로 동작하기 때문에 완전히 같은 객체여야해서 오류가 있는 것 같습니다. validator딴에서 id로 비굫난게 어떤가요??

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/service/CommandCommentService.java
> +		commentValidator.validateWriter(updatableComment, writer);
validatorWriter라는 함수명보다는 동작을 명확히 암시하는 shouldBeSameUser와 같은 이름이 더 흐름을 직관적으로 이해할 수 있을 것 같아요!

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/service/CommandCommentService.java
> +		commentValidator.validateWriter(comment, writer);
이하동문입니다~

2024-01-03 06:59 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	private QnA qnA;
단방향 manyToOne을 Comment쪽에서 하신 이유가 있을까요? 오히려 QnA에서 댓글로 접근하는 플로우가 더 많은 것 같아요

2024-01-03 07:10 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	private QnA qnA;
저는 QnA를 상세 조회할 때 QnA 따로 댓글 따로 조회를 하는 플로우로 생각해서 QnA에서 댓글을 접근하는 횟수가 적다고 생각했어요. 그래서 Comment 쪽으로 단방향을 걸었습니다.

2024-01-03 07:10 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/comment/domain/Comment.java
> +	}
id로 비교하는게 좋아보이네요

2024-01-04 00:56 UTC, jacobhboy approved these changes
굳입니당~

2024-01-04 01:04 UTC, merged