관심 없음 기능 추가
sickgyun/sickgyun-server pull request #47
Opened 2024-01-26 07:01 UTC by jacobhboy

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #46 

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- 관심없음 기능을 개발하였습니다.

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [ ] 테스트를 완료했나요?
- [ ] API 문서를 작성했나요?
- [ ] 코드 컨벤션을 준수했나요?
- [ ] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-01-26 09:47 UTC, Woongbin06 requested changes
수고하셨슴다~ 관심 없음한 걸 취소하는 기능도 있어야 할 거 같아요.

2024-01-26 09:47 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/domain/NotInterested.java
> +	Long partyId;
Id로 간접매핑을 한 이유가 있나요??

2024-01-26 09:47 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/service/implementation/InterestValidator.java
> +		boolean isAlreadyExist = notInterestedRepository.existsByUserIdAndPartyIdAndPartyType(user.getId(), partyId,
메소드 네이밍이 길어지면 디폴트 메소드로 줄일 수도 있을 것 같아요!!

2024-01-26 09:47 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/presentation/InterestController.java
> +
생각을 해보니 Reader는 서비스에서 사용하는 구현체라 프레젠테이션에서 바로 쓰지 말고 서비스를 구현해서 사용하는 게 어떤가요????

2024-01-27 05:37 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/interest/presentation/InterestController.java
> +
이건 나중에 몰아서 개선하죠!

2024-01-27 05:39 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/interest/domain/NotInterested.java
> +	Long partyId;
관심없음과 관련해서는 graphQL 복잡한 쿼리만 날아가는데 그럴 때에는 ID만 매핑하고 쓰는게 훨씬 편하더라구요. 사실 이것보다 저거 두개 복합키로 쓰려고 했는데 따로 클래스 빼자고 하니, 필드가 ID하나인 객체가 만들어져서 일단 저렇게 했습니다 😃

2024-01-27 05:39 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/interest/service/implementation/InterestValidator.java
> +		boolean isAlreadyExist = notInterestedRepository.existsByUserIdAndPartyIdAndPartyType(user.getId(), partyId,
읭 어떻게요??

2024-01-27 05:40 UTC, merged

2024-01-29 09:21 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/service/implementation/InterestValidator.java
> +		boolean isAlreadyExist = notInterestedRepository.existsByUserIdAndPartyIdAndPartyType(user.getId(), partyId,
저거 레파지토리의 메소드 네이밍 말한거였어요!!