채용 조회 기능 구현
sickgyun/sickgyun-server pull request #50
Opened 2024-01-27 05:40 UTC by jacobhboy

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #48 

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- 조회 기능을 구현하였습니당

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [ ] 테스트를 완료했나요?
- [ ] API 문서를 작성했나요?
- [ ] 코드 컨벤션을 준수했나요?
- [ ] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-01-28 06:26 UTC, SEOKKAMONI reviewed
오타를 발견했어용

2024-01-28 06:26 UTC, SEOKKAMONI commented on src/main/java/com/sickgyun/server/reqruit/presentation/ReqruitController.java
> +@RequestMapping("/reqruit")
```suggestion
@RequestMapping("/recruit")
```

2024-01-29 09:05 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/reqruit/presentation/ReqruitController.java
> +@RequestMapping("/reqruit")
와 저 지금까지 reqruit인줄 알고있었네요. 전부 수정하겠습니다.

2024-01-29 09:37 UTC, Woongbin06 requested changes
고생하셨습니당~~

2024-01-29 09:37 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/domain/repository/NotInterestedRepository.java
> +}
전 피알 때 말한 게 이것처럼 레포지토리에서 네이밍이 길어지면 디폴트 메소드로 줄일 수도 있을 거 같아요

2024-01-29 09:37 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/recruit/presentation/dto/RecruitResponse.java
> +	}
정적 팩토리 메소드로 네이밍을 해주는 게 좋을 거 같아요!!

2024-01-29 09:37 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/interest/service/CommandInterestService.java
> +	}
깔끔하네요~~

2024-01-29 09:40 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/interest/domain/repository/NotInterestedRepository.java
> +}
넵~

2024-01-29 09:46 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/recruit/presentation/dto/RecruitResponse.java
> +	}
넵~

2024-01-29 09:59 UTC, Woongbin06 approved these changes
굳굳 좋습니당~

2024-01-29 10:00 UTC, merged