이미지 도메인 추가 및 이미지 저장
sickgyun/sickgyun-server pull request #76
Opened 2024-02-14 03:27 UTC by jacobhboy

## 🎫 관련 이슈
[//]: # (다음 키워드를 사용하면 해당 PR을 머지할 때 자동으로 이슈를 닫을 수 있습니다.)
[//]: # (keyword: close|closes|closed|resolve|resolves|resolved|fix|fixes|fixed)
[//]: # (예시: close #1)

close #74 

<br>

## 🔨 작업 내용
[//]: # (작업 내용을 자세하게 적습니다.)
[//]: # (붙임표 "-" 을 사용해서 목록을 만듭니다.)
[//]: # (예시: 유저 회원가입 API를 만들었습니다.)

- 이미지 추가 및 삭제 구현
 

<br>

## 🏁 확인 사항
[//]: # (PR을 보내기 전 다음 사항을 확인해주세요.)
[//]: # (해당 사항을 모두 이행해야 머지할 수 있습니다.)
[//]: # (- [x] 를 사용해서 완료로 표시할 수 있습니다.)

- [ ] 테스트를 완료했나요?
- [ ] API 문서를 작성했나요?
- [ ] 코드 컨벤션을 준수했나요?
- [ ] 불필요한 로그, 주석, import 등을 삭제했나요?

<br>

## 🙋🏻 덧붙일 말
[//]: # (다음 사항이 있다면 적어주세요.)
[//]: # (PR에 대한 추가 설명)
[//]: # (중점적으로 리뷰받고 싶은 부분)
[//]: # (기타 등등)

2024-02-19 10:04 UTC, Woongbin06 requested changes
수고하셨습다

2024-02-19 10:04 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/image/domain/Image.java
> +	private String fileName;
이미지 도메인을 만든 이유가 있을까요??

2024-02-19 10:04 UTC, Woongbin06 commented on src/main/java/com/sickgyun/server/image/service/implement/ImageDeleter.java
> +		amazonS3.deleteObject(s3Bucket.getS3Bucket(), byId.getFileName());
Image 객체 이름이 byId보단 image가 좋을 거 같아요

2024-02-20 08:41 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/image/domain/Image.java
> +	private String fileName;
s3에 저장된 이미지와 image객체의 생명주기를 똑같이 관리하려고 저렇게 구현했는데, 중간에 방법이 바뀌면서 필요없게 되었네요! 삭제하는 편이 좋을 것 같습니다.

2024-02-20 08:41 UTC, jacobhboy commented on src/main/java/com/sickgyun/server/image/service/implement/ImageDeleter.java
> +		amazonS3.deleteObject(s3Bucket.getS3Bucket(), byId.getFileName());
넵

2024-02-20 08:57 UTC, merged